### ISSUE TITLE
V4.2.x Crash

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#135]
Using new UI, we got this crash after several hours running without problem.
Are the new fragments using different threads?  SimpleDateFormat is not thread safe?

Dear OpenSeizureDetector,

Application is just crashed, please check following error log for more details.

***** UCE HANDLER Library
***** by Rohit Surwase

***** DEVICE INFO
Brand: samsung
Device: a20e
Model: SM-A202F
Manufacturer: samsung
Product: a20eeea
SDK: 30
Release: 11

***** APP INFO
Version: 4.2.1n
Installed On: 2024-01-25 20:19:29
Updated On: 2024-01-25 21:10:21
Current Date: 2024-01-26 05:20:41

***** ERROR LOG
java.lang.ArrayIndexOutOfBoundsException: length=13; index=-644
at sun.util.calendar.BaseCalendar.getCalendarDateFromFixedDate(BaseCalendar.java:453)
at java.util.GregorianCalendar.computeFields(GregorianCalendar.java:2411)
at java.util.GregorianCalendar.computeTime(GregorianCalendar.java:2813)
at java.util.Calendar.updateTime(Calendar.java:3403)
at java.util.Calendar.getTimeInMillis(Calendar.java:1761)
at libcore.util.ZoneInfo$WallTime.mktime(ZoneInfo.java:895)
at android.text.format.Time$TimeCalculator.toMillis(Time.java:1090)
at android.text.format.Time.toMillis(Time.java:752)
at uk.org.openseizuredetector.SdDataSource.faultCheck(SdDataSource.java:873)
at uk.org.openseizuredetector.SdDataSource.access$000(SdDataSource.java:59)
at uk.org.openseizuredetector.SdDataSource$2.run(SdDataSource.java:188)
at java.util.TimerThread.mainLoop(Timer.java:562)
at java.util.TimerThread.run(Timer.java:512)

***** END OF LOG *****

**Comment by jones139** [comment]
This one is serious because it resulted in a silent failure of the system.   

Ironically the crash was in the fault detection code which has not changed for 4 years.

But the actual crash is from the Java Calendar code, not OSD, so not really sure what happened.

I think we'll put the whole fault checking code in a try...catch block, and generate a fault state if an exception is raised.

**Comment by jones139** [comment]
Will re-open if we see it again...

**Comment by jones139** [comment]
Another user has also reported this issue, so pushing a fix to production code to prevent it happening again (V4.1.13)
