### ISSUE TITLE
V4.2.1r Crashes when rotating screen in new user interface

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#142]
Crash during screen rotation

Dear OpenSeizureDetector,

Application is just crashed, please check following error log for more details.

***** UCE HANDLER Library
***** by Rohit Surwase

***** DEVICE INFO
Brand: samsung
Device: a20e
Model: SM-A202F
Manufacturer: samsung
Product: a20eeea
SDK: 30
Release: 11

***** APP INFO
Version: 4.2.1r
Installed On: 2024-01-25 20:19:29
Updated On: 2024-01-31 21:11:34
Current Date: 2024-02-02 11:44:39

***** ERROR LOG
java.lang.IllegalStateException: Fragment FragmentCommon{75574c0} (9c2342b4-3b9c-475c-9cc1-3459ba810276) not attached to a context.
at androidx.fragment.app.Fragment.requireContext(Fragment.java:972)
at androidx.fragment.app.Fragment.getResources(Fragment.java:1036)
at androidx.fragment.app.Fragment.getString(Fragment.java:1058)
at uk.org.openseizuredetector.FragmentCommon.updateUi(FragmentCommon.java:243)
at uk.org.openseizuredetector.FragmentOsdBaseClass$2.run(FragmentOsdBaseClass.java:114)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:246)
at android.app.ActivityThread.main(ActivityThread.java:8653)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

***** END OF LOG *****

**Comment by jones139** [comment]
Fixed in v4.2 1
