### ISSUE TITLE
V4.2.1 - crash editing data sharing event

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#143]
Editing a manual alarm event 

Dear OpenSeizureDetector,

Application is just crashed, please check following error log for more details.

Editing data sharing event 

***** UCE HANDLER Library
***** by Rohit Surwase

***** DEVICE INFO
Brand: samsung
Device: j5y17lte
Model: SM-J530F
Manufacturer: samsung
Product: j5y17ltexx
SDK: 28
Release: 9

***** APP INFO
Version: 4.2.1
Installed On: 2022-04-14 16:19:04
Updated On: 2024-02-02 18:49:00
Current Date: 2024-02-03 07:48:38

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.put(java.lang.String, java.lang.Object)' on a null object reference
at uk.org.openseizuredetector.EditEventActivity$6.onCheckedChanged(EditEventActivity.java:335)
at android.widget.RadioGroup.setCheckedId(RadioGroup.java:194)
at android.widget.RadioGroup.access$600(RadioGroup.java:61)
at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:379)
at android.widget.CompoundButton.setChecked(CompoundButton.java:185)
at android.widget.CompoundButton.toggle(CompoundButton.java:136)
at android.widget.RadioButton.toggle(RadioButton.java:79)
at android.widget.CompoundButton.performClick(CompoundButton.java:141)
at android.view.View.performClickInternal(View.java:7323)
at android.view.View.access$3200(View.java:849)
at android.view.View$PerformClick.run(View.java:27895)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7266)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

***** END OF LOG *****

**Comment by jones139** [comment]
It worked on second attempt.   Maybe the seizure types file had not finished downloading the first time?

**Comment by jones139** [comment]
I think this is fixed in V5.0 - will re-open if it happens again.
