### ISSUE TITLE
Crash when returning from export activity after long screen off

### ISSUE THREAD

**Issue by AroonPro** [OpenSeizureDetector/Android_Pebble_SD#184]
Dear OpenSeizureDetector,

Application is just crashed, please check following error log for more details.

***** OpenSeizureDetector Crash Report 
***** by Graham Jones (using UCE Error handler by Rohit Surwase)

***** DEVICE INFO 
Brand: samsung
Device: a54x
Model: SM-A546B
Manufacturer: samsung
Product: a54xnaeea
SDK: 34
Release: 14

***** APP INFO 
Version: 5.0.0a
Installed On: 2024-02-11 16:45:28
Updated On: 2024-05-01 20:16:53
Current Date: 2024-05-02 03:53:23

***** ERROR LOG 
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean uk.org.openseizuredetector.WebApiConnection.getEvents(uk.org.openseizuredetector.WebApiConnection$JSONObjectCallback)' on a null object reference
	at uk.org.openseizuredetector.LogManagerControlActivity.getRemoteEvents(LogManagerControlActivity.java:254)
	at uk.org.openseizuredetector.LogManagerControlActivity.initialiseServiceConnection(LogManagerControlActivity.java:231)
	at uk.org.openseizuredetector.LogManagerControlActivity.waitForConnection(LogManagerControlActivity.java:206)
	at uk.org.openseizuredetector.LogManagerControlActivity.access$000(LogManagerControlActivity.java:54)
	at uk.org.openseizuredetector.LogManagerControlActivity$1.run(LogManagerControlActivity.java:212)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8893)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

***** END OF LOG *****

**Comment by jones139** [comment]
Do you know if this occurs in V4.2.x as well?  I haven't seen it before, but I don't use the Export Data function.

**Comment by jones139** [comment]
It looks like the WebApiConnection was null for some reason - maybe we are doing things in onStart that should be done in onResume instead?

**Comment by jbmalfilattre** [comment]
Having a look at the code that was causing this null pointer (in "LogManagerControlActivity.java") in the official 5.0.9 version, it seems to me that the underlying problem that caused this crash has long been fixed.
Am I missing something or is there any specific reason why this issue is still open?

**Comment by jones139** [comment]
You are being very busy, thank you!  I think you are right - we did a lot in v5 to reduce crashes, so id suggest we close this one and create a new one if we see something similar with v5.   I have to go through my emails for the last few days - I think i did see a crash report - ill look later.
