### ISSUE TITLE
Crash in ExportActivity when using comma as decimal separator

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#185]
Thank you @aroonpro and @pmithrandir for reporting

***** DEVICE INFO
Brand: OPPO
Device: OP4F39L1
Model: CPH2195
Manufacturer: OPPO
Product: CPH2195EEA
SDK: 33
Release: 13

***** APP INFO
Version: 4.2.7
Installed On: 2023-11-18 15:11:30
Updated On: 2024-04-20 04:02:16
Current Date: 2024-05-02 22:57:53

***** ERROR LOG
java.lang.NumberFormatException: For input string: "2,0"
at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:660)
at uk.org.openseizuredetector.ExportDataActivity.onClick(ExportDataActivity.java:201)
at android.view.View.performClick(View.java:7558)
at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218)
at android.view.View.performClickInternal(View.java:7534)
at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
at android.view.View$PerformClick.run(View.java:29672)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:240)
at android.os.Looper.loop(Looper.java:351)
at android.app.ActivityThread.main(ActivityThread.java:8377)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

**Comment by jones139** [comment]
See also #183

**Comment by jones139** [comment]
I think something along these lines, based on https://codingstrain.com/java-double-parse-string-with-comma/

NumberFormat format = NumberFormat.getInstance(Locale.ITALY);
Number number = format.parse(numStr);
double doubleNum = number.doubleValue();

Just need to find the way of finding our actual locale in Android.

**Comment by pmithrandir** [comment]
https://stackoverflow.com/questions/8188137/decimal-point-or-decimal-comma-in-android

they suggest to use: 
``` 
char separatorChar = DecimalFormatSymbols.getInstance().getDecimalSeparator();
```

**Comment by AroonPro** [comment]
Already found and included in @AroonPro/Android_Pebble_SD/v5.0.0_upstream

Only to say that the decision to important what where and when is @jones139 . Like said in the v5 thread.

**Comment by AroonPro** [comment]
Constants. GLOBAL_CONSANTS.         char CURRENT_USER_DECIMAL_CHARACTER = DecimalFormatSymbols.getInstance().getDecimalSeparator();

  Osdutil:

/**
     *
     * parseToDouble internal OsdUtil Function to read string user input and safely
     * use in further programming, without crashing the main program.
     *
     * Source: Chat with Bing© AI Sources: StackOverFlow
     * */
    public static double parseToDouble(String userInput) {
        try {
            // Replace any user-defined decimal separator with the system default (e.g., '.' or ',')
            String cleanedInput = userInput.replaceFirst(String.valueOf(Constants.GLOBAL_CONSTANTS.CURRENT_USER_DECIMAL_CHARACTER), ".");
            // Parse the cleaned input to a double
            double parsedValue = Double.parseDouble(cleanedInput);
            return parsedValue;
        } catch (NumberFormatException e) {
            // Handle invalid input (e.g., non-numeric characters)
            throw new IllegalArgumentException("Invalid input. Please enter a valid numeric value.");
        }
    }

}

ExportActivity:
            mDuration = OsdUtil.parseToDouble(mDurationTxt.getText().toString());

**Comment by jones139** [comment]
Thanks, I'll pull your code into v4.2 because this one needs fixing.     Then I'm going to say V4.2 is stable enough to publish so we only have two versions to maintain rather than three!

**Comment by jones139** [comment]
I have implemented a  version of ParseToDouble into OsdUils as suggested by @AroonPro.   My version is slightly different because I have used NumberFormat to do the parsing as recommended by the Oracle java documentation.

It seems to work in both English and French, so I think it fixes this issue.
