### ISSUE TITLE
V4.2.8 Crash During Start-Up

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#191]
***** DEVICE INFO
Brand: motorola
Device: sabahl
Model: moto e13
Manufacturer: motorola
Product: sabahl_ge
SDK: 33
Release: 13

***** APP INFO
Version: 4.2.8
Installed On: 2024-05-17 18:50:58
Updated On: 2024-05-17 18:50:58
Current Date: 2024-06-02 17:32:01

***** ERROR LOG
java.lang.IllegalArgumentException: could not get CCC descriptor for characteristic 00002a19-0000-1000-8000-00805f9b34fb
at com.welie.blessed.BluetoothPeripheral.setNotify(BluetoothPeripheral.java:1407)
at com.welie.blessed.BluetoothPeripheral.setNotify(BluetoothPeripheral.java:1385)
at uk.org.openseizuredetector.SdDataSourceBLE2$2.onServicesDiscovered(SdDataSourceBLE2.java:301)
at com.welie.blessed.BluetoothPeripheral$1$1.run(BluetoothPeripheral.java:213)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:8046)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:703)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)

**Comment by jones139** [comment]
We were having a lot of trouble with the system not starting up when using PineTime (Version 0.7) - tried various combinations of re-booting watch and phone, and also trying a different watch.
At some point during this process we got the above crash.
I don't know what was wrong because there were so many bluetooth issues at the time.

Suggest we just catch this error and display a TOAST, because the system will go to FAULT if we do not get notifications working anyway.

**Comment by jones139** [comment]
Have not been able to reproduce this, and have improved the reconnection code in V5.0, so closing this.
