### ISSUE TITLE
V4.2.8 - crash in edit event screen.

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#200]
User reported crash: 

***** DEVICE INFO
Brand: samsung
Device: beyond1q
Model: SM-G973W
Manufacturer: samsung
Product: beyond1qltecs
SDK: 31
Release: 12

***** APP INFO
Version: 4.2.8
Installed On: 2024-06-11 13:24:59
Updated On: 2024-06-11 13:24:59
Current Date: 2024-06-26 11:13:22

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject org.json.JSONObject.put(java.lang.String, java.lang.Object)' on a null object reference
at uk.org.openseizuredetector.EditEventActivity$6.onCheckedChanged(EditEventActivity.java:335)
at android.widget.RadioGroup.setCheckedId(RadioGroup.java:205)
at android.widget.RadioGroup.access$600(RadioGroup.java:67)
at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:390)
at android.widget.CompoundButton.setChecked(CompoundButton.java:238)
at android.widget.CompoundButton.toggle(CompoundButton.java:150)
at android.widget.RadioButton.toggle(RadioButton.java:85)
at android.widget.CompoundButton.performClick(CompoundButton.java:155)
at android.view.View.performClickInternal(View.java:7769)
at android.view.View.access$3800(View.java:910)
at android.view.View$PerformClick.run(View.java:30218)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)

**Comment by jones139** [comment]
I haven't seen this since, so think it is fixed.
