### ISSUE TITLE
Crash from graph drawing library

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#40]
I dropped the phone on the table (from 10-15 cm) and got this crash ...

BR, Andrej

***** UCE HANDLER Library
***** by Rohit Surwase

***** DEVICE INFO
Brand: Nokia
Device: TTG_sprout
Model: Nokia XR20
Manufacturer: HMD Global
Product: TheThing_00EEA
SDK: 30
Release: 11

***** APP INFO
Version: 4.0.0q
Installed On: 2022-03-04 09:29:42
Updated On: 2022-03-04 09:29:42
Current Date: 2022-03-04 09:46:07

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
at android.graphics.Canvas.<init>(Canvas.java:116)
at com.github.mikephil.charting.charts.Chart.onDraw(Chart.java:393)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:149)
at android.view.View.draw(View.java:22366)
at android.view.View.updateDisplayListIfDirty(View.java:21242)
at android.view.View.draw(View.java:22097)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21233)
at android.view.View.draw(View.java:22097)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21233)
at android.view.View.draw(View.java:22097)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21233)
at android.view.View.draw(View.java:22097)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21233)
at android.view.View.draw(View.java:22097)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.updateDisplayListIfDirty(View.java:21233)
at android.view.View.draw(View.java:22097)
at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
at android.view.View.draw(View.java:22369)
at com.android.internal.policy.DecorView.draw(DecorView.java:806)
at android.view.View.updateDisplayListIfDirty(View.java:21242)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4108)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3835)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3106)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1950)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8186)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
at android.view.Choreographer.doCallbacks(Choreographer.java:878)
at android.view.Choreographer.doFrame(Choreographer.java:811)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1041)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:223)
at android.app.ActivityThread.main(ActivityThread.java:7721)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)

***** END OF LOG *****

**Comment by jones139** [comment]
I think I am using a very old version of the graph drawing library - I should really upgrade to the latest version, which might well have fixed this.  Fortunately it only crashes the main activity - the background service continues to run ok, so the system still works after the crash.

**Comment by jones139** [comment]
Reported by another user on the latest version of the app (4.0.7):

​***** DEVICE INFO
Brand: OnePlus
Device: OP515BL1
Model: DN2103
Manufacturer: OnePlus
Product: DN2103EEA
SDK: 31
Release: 12

***** APP INFO
Version: 4.0.7
Installed On: 2022-07-16 18:41:56
Updated On: 2022-08-12 03:26:49
Current Date: 2022-08-27 17:42:01

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
at android.graphics.Canvas.<init>(Canvas.java:113)
at com.github.mikephil.charting.charts.Chart.onDraw(Chart.java:393)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:149)
at android.view.View.draw(View.java:22944)
at android.view.View.updateDisplayListIfDirty(View.java:21758)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:620)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4944)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4636)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3696)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2410)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9466)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1238)
at android.view.Choreographer.doCallbacks(Choreographer.java:992)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1223)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8223)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by jones139** [comment]
Another report of the crash from a user:
***** DEVICE INFO
Brand: OnePlus
Device: OP515BL1
Model: DN2103
Manufacturer: OnePlus
Product: DN2103EEA
SDK: 31
Release: 12

***** APP INFO
Version: 4.0.7
Installed On: 2022-07-16 18:41:56
Updated On: 2022-08-12 03:26:49
Current Date: 2022-09-02 16:30:47

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isMutable()' on a null object reference
at android.graphics.Canvas.<init>(Canvas.java:113)
at com.github.mikephil.charting.charts.Chart.onDraw(Chart.java:393)
at com.github.mikephil.charting.charts.BarLineChartBase.onDraw(BarLineChartBase.java:149)
at android.view.View.draw(View.java:22944)
at android.view.View.updateDisplayListIfDirty(View.java:21758)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4648)
at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4621)
at android.view.View.updateDisplayListIfDirty(View.java:21702)
at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:534)
at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:540)
at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:620)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:4944)
at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4636)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3696)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2410)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9466)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1238)
at android.view.Choreographer.doCallbacks(Choreographer.java:992)
at android.view.Choreographer.doFrame(Choreographer.java:882)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1223)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8223)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by jones139** [comment]
I have upgraded to a later version of the graph drawing library in V4.1.x and have not seen this again so closing for now - will re-open if we see a crash from V4.1.x or later.
