### ISSUE TITLE
Crash because of network error?

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#43]
Dear OpenSeizureDetector,

Application is just crashed, please check following error log for more details.

***** UCE HANDLER Library
***** by Rohit Surwase

***** DEVICE INFO
Brand: samsung
Device: j5y17lte
Model: SM-J530F
Manufacturer: samsung
Product: j5y17ltexx
SDK: 28
Release: 9

***** APP INFO
Version: 4.0.0n
Installed On: 2022-02-20 21:09:08
Updated On: 2022-03-01 14:16:28
Current Date: 2022-03-05 12:09:19

***** ERROR LOG
java.lang.NullPointerException: Attempt to read from field 'byte[] com.android.volley.NetworkResponse.data' on a null object reference
at uk.org.openseizuredetector.WebApiConnection$17.onErrorResponse(WebApiConnection.java:491)
at com.android.volley.Request.deliverError(Request.java:652)
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:216)
at android.app.ActivityThread.main(ActivityThread.java:7266)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

***** END OF LOG *****

**Comment by jones139** [comment]
Removed references sub-components of the error returned by the network requests - I think that should cure it.
Fixed by f4f3da2aa948e2e831284dc131529b984d17f8df
