### ISSUE TITLE
Crash during shutdown

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#45]
During shutdown.

Application is just crashed, please check following error log for more details.

***** UCE HANDLER Library
***** by Rohit Surwase

***** DEVICE INFO
Brand: samsung
Device: gt510wifi
Model: SM-T550
Manufacturer: samsung
Product: gt510wifixx
SDK: 25
Release: 7.1.1

***** APP INFO
Version: 4.0.0q
Installed On: 2019-09-15 21:09:02
Updated On: 2022-03-03 07:44:38
Current Date: 2022-03-10 07:45:45

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.database.sqlite.SQLiteDatabase.execSQL(java.lang.String)' on a null object reference
at uk.org.openseizuredetector.LogManager.writeDatapointToLocalDb(LogManager.java:243)
at uk.org.openseizuredetector.SdServer.logData(SdServer.java:1147)
at uk.org.openseizuredetector.SdServer.onSdDataReceived(SdServer.java:763)
at uk.org.openseizuredetector.SdDataSourceNetwork$DownloadSdDataTask.onPostExecute(SdDataSourceNetwork.java:161)
at uk.org.openseizuredetector.SdDataSourceNetwork$DownloadSdDataTask.onPostExecute(SdDataSourceNetwork.java:118)
at android.os.AsyncTask.finish(AsyncTask.java:667)
at android.os.AsyncTask.-wrap1(AsyncTask.java)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

***** END OF LOG *****

**Comment by jones139** [comment]
I don't know why we got this crash - it looks like there is already an exception clause for it, but added an explicit check for mOsdDb being null before using it.   Fixed by 7d307529b4a5fb7969bd36b4f9098dba60ce4e85
