### ISSUE TITLE
Crash in V4.0.1 when sending SMS

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#49]
For some reason that I can not see, mLocationFinder was null when it tried to send an SMS.   Crash report from user below.

I can't see how this could happen from the code, but it could be another manifestation of the 'not shutting down correctly' issue maybe?

***** DEVICE INFO
Brand: OnePlus
Device: Nord
Model: AC2003
Manufacturer: OnePlus
Product: Nord_EEA
SDK: 30
Release: 11

***** APP INFO
Version: 4.0.1
Installed On: 2022-03-15 17:37:40
Updated On: 2022-03-24 16:23:02
Current Date: 2022-03-24 16:28:04

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'void uk.org.openseizuredetector.LocationFinder.getLocation(uk.org.openseizuredetector.SdLocationReceiver)' on a null object reference
at uk.org.openseizuredetector.SdServer$SmsTimer.onFinish(SdServer.java:1292)
at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loop(Looper.java:245)
at android.app.ActivityThread.main(ActivityThread.java:8024)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by jones139** [comment]
Sending SMS is an important function, so we should add a check that the LocationFinder is not null before trying to use it - then at least an SMS will be sent, even if it does not include the location because of this issue.

**Comment by jones139** [comment]
Added a catch for mLocationFinder being null before using it - logs an error and toast warning if it occurs. 5c633e3fdd051698da2fdcc5c02d3e609d98c349 fixes it.
