### ISSUE TITLE
User Reported Crash - appears to be selecting BLE Data Source with bluetooth permission not granted

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#60]
***** DEVICE INFO
Brand: samsung
Device: r8q
Model: SM-G781W
Manufacturer: samsung
Product: r8qcsx
SDK: 31
Release: 12

***** APP INFO
Version: 4.0.6
Installed On: 2021-11-10 10:52:30
Updated On: 2022-06-27 06:10:47
Current Date: 2022-06-28 14:51:03

***** ERROR LOG
java.lang.RuntimeException: Unable to start service uk.org.openseizuredetector.SdServer@ef1894a with Intent { dat=Start cmp=uk.org.openseizuredetector/.SdServer }: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10338, packageName = uk.org.openseizuredetector, attributionTag = null, token = android.os.BinderProxy@a0e3eb, next = null }: GattService registerClient
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5110)
at android.app.ActivityThread.access$2200(ActivityThread.java:310)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2319)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8663)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.SecurityException: Need android.permission.BLUETOOTH_CONNECT permission for AttributionSource { uid = 10338, packageName = uk.org.openseizuredetector, attributionTag = null, token = android.os.BinderProxy@a0e3eb, next = null }: GattService registerClient
at android.os.Parcel.createExceptionOrNull(Parcel.java:2437)
at android.os.Parcel.createException(Parcel.java:2421)
at android.os.Parcel.readException(Parcel.java:2404)
at android.os.Parcel.readException(Parcel.java:2346)
at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerClient(IBluetoothGatt.java:2698)
at android.bluetooth.BluetoothGatt.registerApp(BluetoothGatt.java:1015)
at android.bluetooth.BluetoothGatt.registerApp(BluetoothGatt.java:977)
at android.bluetooth.BluetoothGatt.connect(BluetoothGatt.java:1109)
at android.bluetooth.BluetoothDevice.connectGatt(BluetoothDevice.java:4061)
at android.bluetooth.BluetoothDevice.connectGatt(BluetoothDevice.java:4004)
at android.bluetooth.BluetoothDevice.connectGatt(BluetoothDevice.java:3967)
at android.bluetooth.BluetoothDevice.connectGatt(BluetoothDevice.java:3938)
at android.bluetooth.BluetoothDevice.connectGatt(BluetoothDevice.java:3912)
at android.bluetooth.BluetoothDevice.connectGatt(BluetoothDevice.java:3890)
at uk.org.openseizuredetector.SdDataSourceBLE.bleConnect(SdDataSourceBLE.java:166)
at uk.org.openseizuredetector.SdDataSourceBLE.start(SdDataSourceBLE.java:125)
at uk.org.openseizuredetector.SdServer.onStartCommand(SdServer.java:283)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5092)
... 9 more

**Comment by jones139** [comment]
The expected behaviour is that it should ask for the required permission, not crash.

**Comment by jones139** [comment]
Should be fixed in V4.1.9
