### ISSUE TITLE
Data log manager gets very slow over time and crashes sometimes

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#63]
User reported issue:
***** APP INFO
Version: 4.0.6
Installed On: 2022-06-10 12:26:29
Updated On: 2022-07-10 18:45:04
Current Date: 2022-08-06 06:17:57

***** ERROR LOG
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@5a0098d is not valid; is your activity running?
at android.view.ViewRootImpl.setView(ViewRootImpl.java:922)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:105)
at android.widget.Toast$TN.handleShow(Toast.java:747)
at android.widget.Toast$TN$2.handleMessage(Toast.java:622)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6823)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by jones139** [comment]
I think the main issue is with the local database getting big and the query taking too long 

- quick fix is to prune the database to 7 days rather than 28.
- Really need to make database access a background task to avoid hanging.
- But I don't know if this was the cause of the above error or not...

**Comment by jones139** [comment]
Will close this for now and see if the work-around in V4.0.7 fixes it - will re-open if not.
