### ISSUE TITLE
Server Crashes on Android 5.0

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#8]
Version 2.0a reported as crashing when connecting to Pebble Time from Android 5.0.

**Comment by jones139** [comment]
I think that this is related to ToneGenerator that makes the beep noises, but it does not happen on all Android 5 devices.

**Comment by jones139** [comment]
Maybe not an Android 5 issue - several users reported this error:
Error Report collected on : Mon May 23 00:58:35 BST 2016

System Information :
Locale: en_GB
Version: 2.0.3
Package: uk.org.openseizuredetector
Phone Model: VF695
Android Version: 4.4.2
Board: VF695
Brand: Vodafone
Device: VF695
Host: slave-176
ID: KOT49H
Model: VF695
Product: VF695
Type: user
Total Internal memory: 2177179648
Available Internal memory: 858656768

Stack Trace:
java.lang.RuntimeException: Can't create handler inside thread that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:208)
at android.os.Handler.<init>(Handler.java:122)
at android.widget.Toast$TN.<init>(Toast.java:327)
at android.widget.Toast.<init>(Toast.java:92)
at android.widget.Toast.makeText(Toast.java:241)
at uk.org.openseizuredetector.OsdUtil.showToast(OsdUtil.java:186)
at uk.org.openseizuredetector.SdServer.beep(SdServer.java:486)
at uk.org.openseizuredetector.SdServer.faultWarningBeep(SdServer.java:500)
at uk.org.openseizuredetector.SdServer.onSdDataFault(SdServer.java:472)
at uk.org.openseizuredetector.SdDataSourcePebble.getPebbleStatus(SdDataSourcePebble.java:476)
at uk.org.openseizuredetector.SdDataSourcePebble$1.run(SdDataSourcePebble.java:126)
at java.util.Timer$TimerImpl.run(Timer.java:284)

**** End of current Report ***
