### ISSUE TITLE
Pending Intent Error

### ISSUE THREAD

**Issue by AroonPro** [OpenSeizureDetector/Android_Pebble_SD#80]
uk.org.openseizuredetector.SdServer.showNotification(SdServer.java:518)
	
Possible created by Context (this, getApplicationContext or mContext) migration to applicable Context. 

To be investigated 

***** UCE HANDLER Library 
***** by Rohit Surwase 

***** DEVICE INFO 
Brand: samsung
Device: a53x
Model: SM-A536B
Manufacturer: samsung
Product: a53xnaeea
SDK: 33
Release: 13

***** APP INFO 
Version: 4.2.4d
Installed On: 2022-11-22 01:24:27
Updated On: 2023-05-30 21:46:48
Current Date: 2023-05-31 19:07:51

***** ERROR LOG 
java.lang.IllegalArgumentException: uk.org.openseizuredetector: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:408)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:491)
	at android.app.PendingIntent.getActivity(PendingIntent.java:477)
	at android.app.PendingIntent.getActivity(PendingIntent.java:441)
	at uk.org.openseizuredetector.SdServer.showNotification(SdServer.java:518)
	at uk.org.openseizuredetector.SdServer.onSdDataFault(SdServer.java:810)
	at uk.org.openseizuredetector.SdDataSource.getStatus(SdDataSource.java:715)
	at uk.org.openseizuredetector.SdDataSource$1.run(SdDataSource.java:153)
	at java.util.TimerThread.mainLoop(Timer.java:563)
	at java.util.TimerThread.run(Timer.java:513)

***** END OF LOG *****

**Comment by jones139** [comment]
Thanks - from the error text it looks like we need to change the flags attached to the intent associated with the status bar notification.    I'll have a go at it in V4 1.x because I have had to change the target to sdk31 so it will be an issue in that version when it is published

**Comment by jones139** [comment]
Should be fixed in V4.1.4 and higher (https://github.com/OpenSeizureDetector/Android_Pebble_SD/commit/36ba4e2f778b2cbf623acc178d9a87f14ab1af0c)

**Comment by AroonPro** [comment]
Good to see your solution. I lost track of setting both flags. I thought in
creating a choice upon SDK_INT. I will pull in your 4.1.x to 4.2.x because
I've seen that the code is not entirely in sync.

Op wo 31 mei 2023 21:06 schreef Graham Jones ***@***.***>:

**Comment by jones139** [comment]
Fixed in V4.1.x so closing.
