### ISSUE TITLE
V4.1.4 - User reported crash on starting.

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#90]
***** DEVICE INFO
Brand: google
Device: bluejay
Model: Pixel 6a
Manufacturer: Google
Product: bluejay
SDK: 33
Release: 13

***** APP INFO
Version: 4.1.4
Installed On: 2023-04-23 13:48:17
Updated On: 2023-06-05 19:57:53
Current Date: 2023-06-06 17:13:45

***** ERROR LOG
java.lang.IllegalArgumentException: uk.org.openseizuredetector: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:484)
at android.app.PendingIntent.getActivity(PendingIntent.java:470)
at android.app.PendingIntent.getActivity(PendingIntent.java:434)
at uk.org.openseizuredetector.SdServer.showEventNotification(SdServer.java:1672)
at uk.org.openseizuredetector.SdServer.lambda$checkEvents$0$uk-org-openseizuredetector-SdServer(SdServer.java:1595)
at uk.org.openseizuredetector.SdServer$$ExternalSyntheticLambda0.accept(Unknown Source:2)
at uk.org.openseizuredetector.WebApiConnection_osdapi$10.onResponse(WebApiConnection_osdapi.java:300)
at uk.org.openseizuredetector.WebApiConnection_osdapi$10.onResponse(WebApiConnection_osdapi.java:291)
at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:82)
at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:29)
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:102)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7884)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

***** END OF LOG *****

**Comment by jones139** [comment]
I don't know why I didn't see this during testing - must be linked to the check for un-validated events I think.
