### ISSUE TITLE
V4.0.7 - Crash during data sharing authentication?

### ISSUE THREAD

**Issue by jones139** [OpenSeizureDetector/Android_Pebble_SD#99]
User reported crash:
***** DEVICE INFO
Brand: samsung
Device: r8q
Model: SM-G781U
Manufacturer: samsung
Product: r8qsqx
SDK: 33
Release: 13

***** APP INFO
Version: 4.0.7
Installed On: 2023-05-06 10:25:28
Updated On: 2023-05-06 10:25:28
Current Date: 2023-06-11 09:33:57

***** ERROR LOG
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.getString(java.lang.String)' on a null object reference
at uk.org.openseizuredetector.AuthenticateActivity.lambda$updateUi$1$uk-org-openseizuredetector-AuthenticateActivity(AuthenticateActivity.java:192)
at uk.org.openseizuredetector.AuthenticateActivity$$ExternalSyntheticLambda1.accept(Unknown Source:2)
at uk.org.openseizuredetector.WebApiConnection_osdapi$20.onErrorResponse(WebApiConnection_osdapi.java:558)
at com.android.volley.Request.deliverError(Request.java:652)
at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:104)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

***** END OF LOG *****

**Comment by jones139** [comment]
Need to check if this is fixed in V4.1.6 or not....

**Comment by jones139** [comment]
Was still there in V4.1.6 - it was catching a JSON exception for corrupt data, but not for NullPointerException if no data was returned at a ll.  Fixed in V4.1.7.
